# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e667f646ff87968324f37c23d05aec388235958239160a74c484cdd70cba345f30b055e1ba0da1b1b66dfccd64e648c76281eef8678dfafa26ec673c33eef57b

test:
  secret_key_base: 95202c823cfa7a686c9300b9b9cd3b886cd2903f0d9c36a2aee5975db7611eda8052f57105540f053582a2906eaad55e3fc60744fe5c4626a539b18f8d6c59d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
